theme: jekyll-theme-cayman
title: I am Arnold!
name: ArnoldZhang
location: Shanghai
company: mtdp
company_url: /
github_username: arnoldzhang
github_url: https://github.com/arnoldczhang
navs:
  - label: about
    href: /about
  - label: open-source
    href: /open-source
