theme: jekyll-theme-cayman
title: I am Arnold!
name: ArnoldZhang
location: Shanghai
email: arnold.c.zhang@gmail.com
company: mtdp
company_url: /
github_username: arnoldzhang
github_url: https://github.com/arnoldczhang
skill_software_keywords:
  - javascript
navs:
  - label: about
    href: /about
  - label: open-source
    href: /open-source
